name: rotating-word-api
description: Generate a rotating random word with translations in 23 languages for iPhone widget
enabled: true
tags:
  - api
  - word-of-day
  - llm
triggers:
  - type: manual
inputs: 
  - name: recent_words
    type: array
    required: false
steps:
  - name: generate_word
    type: ai.prompt
    with:
      temperature: 1
      prompt: |
        You are a Random Word API that returns JSON responses. Follow these steps:

        1. Generate one random English word suitable for language learning (intermediate difficulty) 
        that is not in this list {{ inputs.recent_words }}.

        2. Translate it into ALL of these languages:
        Arabic (ar), Cantonese (yue), Dutch (nl), French (fr), German (de), Greek (el),
        Hebrew (he), Hindi (hi), Indonesian (id), Italian (it), Japanese (ja), Khmer (km),
        Korean (ko), Mandarin (zh), Polish (pl), Portuguese (pt), Russian (ru), Spanish (es),
        Swahili (sw), Tagalog (tl), Thai (th), Turkish (tr), Vietnamese (vi)

        3. For languages with non-Latin scripts (ar, el, he, hi, ja, km, ko, ru, th, yue, zh), 
        show romanization FIRST, then the native script in parentheses.

        4. Return ONLY valid JSON with translations sorted alphabetically by language code.

        Example response (fields and order are illustrative):
        {
          "word": "the word",
          "definition": "brief definition (max 50 chars)",
          "translations": {
            "ar": "tarjama (ترجمة)",
            "de": "Übersetzung",
            "el": "metáfrasi (μετάφραση)",
            "es": "traducción",
            "fr": "traduction",
            "he": "tirgum (תרגום)",
            "hi": "anuvaad (अनुवाद)",
            "id": "terjemahan",
            "it": "traduzione",
            "ja": "hon'yaku (翻訳)",
            "km": "kaa bak brae (ការបកប្រែ)",
            "ko": "beonyeok (번역)",
            "nl": "vertaling",
            "pl": "tłumaczenie",
            "pt": "tradução",
            "ru": "perevod (перевод)",
            "sw": "tafsiri",
            "th": "kaan plae (การแปล)",
            "tl": "pagsasalin",
            "tr": "çeviri",
            "vi": "dịch thuật",
            "yue": "faan1 jik6 (翻譯)",
            "zh": "fānyì (翻译)"
          }
        }

        Rules:
        - No markdown, no code blocks, no explanations
        - Just raw JSON
        - Keep definition under 50 characters
        - For non-Latin scripts: romanization FIRST, then native script in parentheses
        - Sort translations alphabetically by language code
  - name: log_response
    type: console
    with:
      message: ${{steps.generate_word.output.content}}
